import { Inter } from "next/font/google";
import "./globals.css"
import { FaExclamationTriangle, FaFacebook, FaGithub, FaInstagram, FaLinkedin, FaPhoneAlt, FaVoicemail } from "react-icons/fa";
import { TwitterLogo } from "phosphor-react";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Sahadat Portfolio ",
  description: "Generated by create next app",
};
import { MdMarkEmailRead } from "react-icons/md";
import { Toaster } from "react-hot-toast";

export default function RootLayout({ children }) {
  return (
    <html  lang="en">

<body className={`${inter.className} bg-gray-800 `}>
<div><Toaster/></div>
        {children}
        {/* footer */}
        <footer className="flex  items-center  p-4 bg-neutral text-neutral-content ">


         <div className=" w-full flex justify-around items-center">


          <aside className="items-center grid-flow-col">
             {/* email */}
    
          <button className="flex justify-center items-center  gap-4 rounded-full">
          <MdMarkEmailRead className="text-4xl" /> sahadat40228@gamil.com

          </button>
    <button className="mt-2 flex justify-center items-center gap-4">
    <FaPhoneAlt className="text-2xl" />
    01740228022
    </button>
            <p className="mt-3">Copyright © 2024 - All right reserved</p>
          </aside>

         <div className="flex flex-row gap-x-6 rounded-xl  mt-4">
          <button className="border-b rounded-md p-1">Home</button>  
          <button className="border-b rounded-md p-1">About</button>  
          <button className="border-b rounded-md p-1">Skills</button>  
          <button className="border-b rounded-md p-1">Projects</button>  
          <button className="border-b rounded-md p-1">Contact</button>  
          </div>

          <div className="flex flex-row gap-x-6 rounded-xl p-2 mt-4">
          
       
        {/* github */}
        <a href="https://github.com/Sakibft" target="_blank">
          <button className="text-3xl rounded-full">
            <FaGithub />
          </button>
        </a>
         {/* twitter
         <a href="https://x.com/Sakib2040" target="_blank">
          <button className="text-3xl rounded-full">
            <TwitterLogo />
          </button>
        </a> */}
           {/* linkedin */}
           <button className="text-3xl rounded-full">
          <FaLinkedin />
        </button>
        {/* instagram */}
        <a href="https://www.instagram.com/sakibsarker31/" target="_blank">
          <button className="text-3xl rounded-full">
            <FaInstagram />
          </button>
        </a>
        {/* facebook */}
        <a href="https://www.facebook.com/profile.php?id=100086958673992" target="_blank">
          <button className="text-3xl rounded-full">
            <FaFacebook />
          </button>
        </a>
      </div>
         </div>
      
        </footer>
      </body>
    </html>
  );
}
